spring.application.name=pedidos

server.port=8080

db.name=parceria_sustentavel_dev
db.url=localhost
db.port=6060

spring.datasource.url=jdbc:postgresql://${db.url}:${db.port}/${db.name}
spring.datasource.username=lyra
spring.datasource.password=parceria_sustentavel_dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=pedidos

spring.flyway.enabled=true
spring.flyway.schemas=pedidos
spring.flyway.default-schema=pedidos

eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka

eureka.instance.instance-id=${spring.application.name}:${random.int}