spring.application.name=gateway
server.port=8082

eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka

spring.cloud.gateway.server.webmvc.routes[0].id=pedidos-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8080
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/pedidos/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=pagamentos-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:9000
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/pagamentos/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1