spring.application.name=pagamentos

server.port=9000
server.tomcat.connection-timeout=12000000

db.name=parceria_sustentavel_dev
db.url=localhost
db.port=6060

eureka.client.serviceUrl.defaultZone=http://localhost:8081/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:postgresql://${db.url}:${db.port}/${db.name}
spring.datasource.username=lyra
spring.datasource.password=parceria_sustentavel_dev
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=pagamento

spring.flyway.enabled=true
spring.flyway.schemas=pagamento
spring.flyway.default-schema=pagamento

resilience4j.circuitbreaker.instances.atualizaPedido.slidingWindowSize: 3
resilience4j.circuitbreaker.instances.atualizaPedido.minimumNumberOfCalls: 2
resilience4j.circuitbreaker.instances.atualizaPedido.waitDurationInOpenState: 50s